apiVersion: v1
kind: PersistentVolume
metadata:
  name: cifs-csi-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  csi:
    driver: smb.csi.k8s.io
    volumeAttributes:
      source: //4.234.121.184/sambashare
    volumeHandle: cifs-storage-samba-share
    nodeStageSecretRef:
      name: smbcreds
      namespace: default
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - vers=3.0
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem