apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myapp-cifs-csi-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: cifs-csi-pv
  volumeMode: Filesystem
  storageClassName: ""